apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: olla-ui-tls
spec:
  dnsNames:
    - demo.olla.finance
  issuerRef:
    kind: ClusterIssuer
    name: olla-issuer-production
  secretName: olla-ui-tls
