apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# testnet overlay — triggers frontend deployment workflow on push to testnet branch
namespace: olla-prod

labels:
  - pairs:
      variant: testnet
    includeSelectors: true

resources:
  - ../../base

images:
  - name: registry.digitalocean.com/olla-containers/olla-ui
    newTag: testnet-latest
