apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: olla-prod

resources:
  - ../../base

images:
  - name: registry.digitalocean.com/olla-containers/olla-ui
    newTag: testnet-latest
