apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: olla-prod

resources:
  - namespace.yaml
  - gateway.yaml
  - cluster-issuer.yaml
  - certificate.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
